<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>MainWindow</name>
    <message>
        <location filename="SaveState_gui.py" line="371"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="406"/>
        <source>Nascondi Log</source>
        <translation>hide log</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="692"/>
        <source>Operazione in Corso</source>
        <translation>Operation in Progress</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="506"/>
        <source>Errore Traduzione</source>
        <translation>Translation Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="508"/>
        <source>Impossibile caricare il file di traduzione per l&apos;inglese ({0}).
L&apos;interfaccia rimarrà in italiano.</source>
        <translation>Unable to upload the translation file for English ({0}).
The interface will remain in Italian.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="599"/>
        <source>Profilo &apos;{0}&apos; eliminato.</source>
        <translation>Profile ‘{0}’ deleted.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="643"/>
        <source>Errore Configurazione</source>
        <translation>Configuration Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="643"/>
        <source>Impostazioni necessarie (percorso base, max backup, max dimensione sorgente) non trovate o non valide!</source>
        <translation>Required settings (base path, max backup, max source size) not found or invalid!</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="646"/>
        <source>Errore Percorso Sorgente</source>
        <translation>Source Path Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="646"/>
        <source>La cartella sorgente dei salvataggi non esiste o non è valida:
{0}</source>
        <translation>The source folder of the saves does not exist or is invalid:
{0}</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="668"/>
        <source>Spazio su disco insufficiente per il backup!

Spazio libero: {0:.2f} GB
Spazio minimo richiesto: {1} GB

Libera spazio sul disco di destinazione (&apos;{2}&apos;) o disabilita il controllo nelle impostazioni.</source>
        <translation>Insufficient disk space for backup!

Free space: {0:.2f} GB
Minimum space required: {1} GB

Free up space on target disk (&apos;{2}&apos;) or disable control in settings.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="669"/>
        <source>Spazio Disco Insufficiente</source>
        <translation>Insufficient Disk Space</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="674"/>
        <source>Errore nel controllo dello spazio: il percorso di backup specificato non sembra essere valido o accessibile:
{0}</source>
        <translation>Error checking space: the specified backup path does not appear to be valid or accessible:
{0}</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="675"/>
        <source>Errore Percorso Backup</source>
        <translation>Backup Path Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="679"/>
        <source>Si è verificato un errore durante il controllo dello spazio libero sul disco:
{0}</source>
        <translation>An error occurred while checking the free disk space:
{0}</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="680"/>
        <source>Errore Controllo Spazio</source>
        <translation>Space Control Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="692"/>
        <source>Un backup o ripristino è già in corso. Attendi il completamento.</source>
        <translation>A backup or restore is already in progress. Wait for completion.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="695"/>
        <source>Avvio backup per &apos;{0}&apos;...</source>
        <translation>Start backup for &apos;{0}&apos;...</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="728"/>
        <source>Avvio ripristino per &apos;{0}&apos;...</source>
        <translation>Restart restoration for ‘{0}’...</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="734"/>
        <source>Ripristino annullato.</source>
        <translation>Restore cancelled.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="735"/>
        <source>Nessun backup selezionato per il ripristino.</source>
        <translation>No backup selected for recovery.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="736"/>
        <source>Selezione backup annullata.</source>
        <translation>Backup selection canceled.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="749"/>
        <source>Operazione terminata senza messaggio.</source>
        <translation>Operation terminated with no message.</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="749"/>
        <source>Completato: {0}</source>
        <translation>Completed: {0}</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="750"/>
        <source>ERRORE: {0}</source>
        <translation>ERROR: {0}</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="753"/>
        <source>Errore Operazione</source>
        <translation>Operation Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="776"/>
        <source>Creazione Collegamento</source>
        <translation>Link Creation</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="778"/>
        <source>Errore Creazione Collegamento</source>
        <translation>Link Creation Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="372"/>
        <source>Nuovo Profilo Manuale</source>
        <translation>New Manual Profile</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="285"/>
        <source>Console Log</source>
        <translation>Console Log</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="373"/>
        <source>Gestisci Giochi Steam</source>
        <translation>Manage Steam Games</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="374"/>
        <source>Elimina Profilo</source>
        <translation>Delete Profile</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="155"/>
        <location filename="SaveState_gui.py" line="375"/>
        <source>Esegui Backup</source>
        <translation>Run Backup</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="408"/>
        <source>Mostra Log</source>
        <translation>Show Log</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="159"/>
        <location filename="SaveState_gui.py" line="376"/>
        <source>Ripristina da Backup</source>
        <translation>Restore from Backup</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="164"/>
        <location filename="SaveState_gui.py" line="377"/>
        <source>Gestisci Backup</source>
        <translation>manage backup</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="168"/>
        <location filename="SaveState_gui.py" line="378"/>
        <source>Apri Cartella Backup</source>
        <translation>Open Backup folder</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="191"/>
        <source>Crea collegamento backup sul desktop</source>
        <translation>Create desktop backup shortcut</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="209"/>
        <location filename="SaveState_gui.py" line="381"/>
        <source>Profili Salvati</source>
        <translation>saved profiles</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="215"/>
        <location filename="SaveState_gui.py" line="383"/>
        <source>Azioni sul Profilo Selezionato</source>
        <translation>Profile Action</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="226"/>
        <source>Crea profilo da mondo Minecraft</source>
        <translation>Create profile from Minecraft world</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="248"/>
        <location filename="SaveState_gui.py" line="385"/>
        <source>Azioni Generali</source>
        <translation>General Action</translation>
    </message>
</context>
<context>
    <name>ManageBackupsDialog</name>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="20"/>
        <source>Gestisci Backup per {0}</source>
        <translation>Manage Backup for {0}</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="27"/>
        <source>Elimina Selezionato</source>
        <translation>Delete Selected</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="34"/>
        <source>Chiudi</source>
        <translation>Close</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="42"/>
        <source>Backup esistenti per &apos;{0}&apos;:</source>
        <translation>Existing backups for &apos;{0}&apos;:</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="71"/>
        <source>Nessun backup trovato.</source>
        <translation>No backups found.</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="90"/>
        <source>Conferma Eliminazione</source>
        <translation>Confirm Deletion</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="94"/>
        <source>Sei sicuro di voler eliminare PERMANENTEMENTE il file di backup:

{0}

Questa azione non può essere annullata!</source>
        <translation>Are you sure you want to PERMANENTLY delete the backup file:

{0}

This action cannot be undone!</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="106"/>
        <source>Successo</source>
        <translation>Success</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="109"/>
        <source>Errore Eliminazione</source>
        <translation>Error Deleting</translation>
    </message>
</context>
<context>
    <name>MinecraftWorldsDialog</name>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="25"/>
        <source>Seleziona Mondo Minecraft</source>
        <translation>Select Minecraft World</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="31"/>
        <source>Seleziona il mondo per cui creare un profilo:</source>
        <translation>Select the world for which to create a profile:</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="38"/>
        <source>Nessun mondo trovato nella cartella &apos;saves&apos; di Minecraft.
Verifica che Minecraft Java Edition sia installato correttamente.</source>
        <translation>No world found in Minecraft &apos;saves&apos; folder.
Verify that Minecraft Java Edition is installed correctly.</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Errore Selezione</source>
        <translation>Error Selection</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Impossibile recuperare i dati del mondo selezionato.</source>
        <translation>Unable to retrieve data from the selected world.</translation>
    </message>
</context>
<context>
    <name>RestoreDialog</name>
    <message>
        <location filename="dialogs/restore_dialog.py" line="18"/>
        <source>Ripristina Backup per {}</source>
        <translation>Restore Backup for {}</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="37"/>
        <source>Nessun backup trovato per questo profilo.</source>
        <translation>No backups found for this profile.</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="52"/>
        <source>Ripristina Selezionato</source>
        <translation>Restore Selected</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="63"/>
        <source>Seleziona il backup da cui ripristinare:</source>
        <translation>Select the backup to restore from:</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="dialogs/settings_dialog.py" line="26"/>
        <location filename="dialogs/settings_dialog.py" line="143"/>
        <source>Impostazioni Applicazione</source>
        <translation>Application Settings</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="36"/>
        <location filename="dialogs/settings_dialog.py" line="144"/>
        <source>Percorso Base Backup</source>
        <translation>Basic Backup Path</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="156"/>
        <source>Standard (Consigliato)</source>
        <translation>Standard (Recommended)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="157"/>
        <source>Massima (Più Lento)</source>
        <translation>Maximum (Slowest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="160"/>
        <source>Nessuna (Più Veloce)</source>
        <translation>None (Fastest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="145"/>
        <source>Dimensione Massima Sorgente per Backup</source>
        <translation>Maximum Source Size for Backup</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="146"/>
        <source>Numero Massimo Backup per Profilo</source>
        <translation>Maximum Number of Backups per Profile</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="148"/>
        <source>Compressione Backup (.zip)</source>
        <translation>Backup Compression (.zip)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="149"/>
        <source>Controllo Spazio Libero Disco</source>
        <translation>Checking Disk Free Space</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="150"/>
        <source>Abilita controllo spazio prima del backup (minimo {0} GB)</source>
        <translation>Enable space check before backup (minimum {0} GB)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="167"/>
        <source>Sfoglia...</source>
        <translation>Browse...</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="169"/>
        <source>Salva</source>
        <translation>Save</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="171"/>
        <source>Annulla</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="185"/>
        <source>Seleziona Cartella Base per i Backup</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.Select Base Folder for Backups</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="213"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="213"/>
        <source>Impossibile validare il percorso.</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.SelectCannot validate path.ona Base Folder for Backups.</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="218"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
</context>
<context>
    <name>SteamDialog</name>
    <message>
        <location filename="dialogs/steam_dialog.py" line="48"/>
        <source>Searching for Steam installation...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="51"/>
        <source>Error: Steam installation not found.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="52"/>
        <source>Searching for Steam libraries...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="55"/>
        <source>Error: No Steam libraries found.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="56"/>
        <source>Scanning installed games...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="59"/>
        <source>Searching for Steam user data...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="64"/>
        <source>Found {0} games. Ready.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="135"/>
        <source>Selezione Profilo Steam</source>
        <translation>Steam Profile Selection</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="136"/>
        <source>Trovati multipli profili Steam.
Seleziona quello corretto (di solito il più recente):</source>
        <translation>Found multiple Steam profiles.
Select the correct one (usually the most recent):</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="153"/>
        <source>Error selecting profile.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="156"/>
        <source>Configuration cancelled (no profile selected).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="160"/>
        <source>Configuration cancelled (empty profile selection?).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="162"/>
        <source>Searching path for &apos;{0}&apos;...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="173"/>
        <source>Found {0} possible paths.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="254"/>
        <location filename="dialogs/steam_dialog.py" line="266"/>
        <source>Configuration cancelled.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="263"/>
        <source>Configuration cancelled (invalid manual path).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="272"/>
        <source>Profile &apos;{0}&apos; configured with path: {1}</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="278"/>
        <source>Error saving profiles.</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>mw</name>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="48"/>
        <location filename="gui_components/profile_creation_manager.py" line="62"/>
        <location filename="gui_components/profile_creation_manager.py" line="72"/>
        <location filename="gui_components/profile_creation_manager.py" line="216"/>
        <location filename="gui_components/profile_creation_manager.py" line="495"/>
        <source>Errore Percorso</source>
        <translation>Path Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="48"/>
        <location filename="gui_components/profile_creation_manager.py" line="495"/>
        <source>Il percorso non può essere vuoto.</source>
        <translation>The path cannot be empty.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="64"/>
        <source>Non è possibile usare una radice del drive (&apos;{0}&apos;) come cartella dei salvataggi per &apos;{1}&apos;.
Per favore, scegli o crea una sottocartella specifica.</source>
        <translation>Cannot use a root drive (&apos;{0}&apos;) as a save folder for &apos;{1}&apos;.
Please choose or create a specific subfolder.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="73"/>
        <source>Il percorso specificato non esiste o non è una cartella valida:
&apos;{0}&apos;</source>
        <translation>The specified path does not exist or is not a valid folder:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="87"/>
        <source>Nuovo Profilo</source>
        <translation>New Profile</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="87"/>
        <source>Inserisci un nome per il nuovo profilo:</source>
        <translation>Enter a name for the new profile:</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="95"/>
        <location filename="gui_components/profile_creation_manager.py" line="210"/>
        <location filename="gui_components/profile_creation_manager.py" line="327"/>
        <source>Errore Nome Profilo</source>
        <translation>Profile Name Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="96"/>
        <source>Il nome del profilo (&apos;{0}&apos;) contiene caratteri non validi o è vuoto dopo la pulizia.</source>
        <translation>The profile name (&apos;{0}&apos;) contains invalid characters or is empty after cleanup.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="101"/>
        <location filename="gui_components/profile_creation_manager.py" line="130"/>
        <location filename="gui_components/profile_creation_manager.py" line="238"/>
        <location filename="gui_components/profile_creation_manager.py" line="518"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="101"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già.</source>
        <translation>A profile called &apos;{0}&apos; already exists.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="105"/>
        <source>Ora inserisci il percorso COMPLETO per i salvataggi del profilo:
&apos;{0}&apos;</source>
        <translation>Now enter the FULL path to your profile saves:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="106"/>
        <source>Percorso Salvataggi</source>
        <translation>Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="126"/>
        <source>Successo</source>
        <translation>Success</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="126"/>
        <source>Profilo &apos;{0}&apos; creato e salvato.</source>
        <translation>Profile &apos;{0}&apos; created and saved.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="127"/>
        <location filename="gui_components/profile_creation_manager.py" line="236"/>
        <location filename="gui_components/profile_creation_manager.py" line="516"/>
        <source>Profilo &apos;{0}&apos; creato.</source>
        <translation>Profile &apos;{0}&apos; created.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="130"/>
        <location filename="gui_components/profile_creation_manager.py" line="518"/>
        <source>Impossibile salvare il file dei profili.</source>
        <translation>Unable to save profile file.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="151"/>
        <source>Ricerca cartella salvataggi Minecraft...</source>
        <translation>minecraft save folders search...</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="158"/>
        <location filename="gui_components/profile_creation_manager.py" line="175"/>
        <source>Errore Minecraft</source>
        <translation>Minecraft Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="158"/>
        <source>Errore imprevisto durante la ricerca della cartella Minecraft.</source>
        <translation>Unexpected error when searching minecraft folder.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="159"/>
        <source>Errore ricerca Minecraft.</source>
        <translation>Minecraft search error.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="164"/>
        <source>Cartella Non Trovata</source>
        <translation>folder not found</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="165"/>
        <source>Impossibile trovare la cartella dei salvataggi standard di Minecraft (.minecraft/saves).
Assicurati che Minecraft Java Edition sia installato.</source>
        <translation>Unable to find the standard Minecraft saves folder (.minecraft/saves).
Make sure Minecraft Java Edition is installed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="166"/>
        <source>Cartella Minecraft non trovata.</source>
        <translation>Minecraft folder not found.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="169"/>
        <source>Lettura mondi Minecraft...</source>
        <translation>Reading Minecraft worlds...</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="175"/>
        <source>Errore imprevisto durante la lettura dei mondi Minecraft.</source>
        <translation>Unexpected error while reading Minecraft worlds.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="176"/>
        <source>Errore lettura mondi Minecraft.</source>
        <translation>Minecraft worlds read error.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="181"/>
        <source>Nessun Mondo Trovato</source>
        <translation>No World Found</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="182"/>
        <source>Nessun mondo trovato nella cartella:
{0}</source>
        <translation>No world found in the folder:
{0}</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="183"/>
        <source>Nessun mondo Minecraft trovato.</source>
        <translation>No Minecraft worlds found.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="190"/>
        <source>Errore Interfaccia</source>
        <translation>Interface Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="190"/>
        <source>Impossibile creare la finestra di selezione dei mondi.</source>
        <translation>Unable to create the worlds selection window.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="193"/>
        <source>Pronto.</source>
        <translation>Ready.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="203"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="203"/>
        <source>Nome del mondo selezionato non valido.</source>
        <translation>Name of selected world invalid.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="211"/>
        <source>Il nome del mondo (&apos;{0}&apos;) contiene caratteri non validi o è vuoto dopo la pulizia.</source>
        <translation>The world name (&apos;{0}&apos;) contains invalid characters or is empty after cleanup.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="216"/>
        <source>Il percorso del mondo selezionato (&apos;{0}&apos;) non è valido.</source>
        <translation>The selected world path (&apos;{0}&apos;) is invalid.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="222"/>
        <location filename="gui_components/profile_creation_manager.py" line="332"/>
        <source>Profilo Esistente</source>
        <translation>Existing Profile</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="223"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già.
Scegli un altro mondo o rinomina il profilo esistente.</source>
        <translation>A profile named &apos;{0}&apos; already exists.
Choose another world or rename the existing profile.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="234"/>
        <location filename="gui_components/profile_creation_manager.py" line="515"/>
        <source>Profilo Creato</source>
        <translation>Profile Created</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="235"/>
        <source>Profilo &apos;{0}&apos; creato con successo per il mondo Minecraft.</source>
        <translation>&apos;{0}&apos; profile successfully created for the Minecraft world.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="238"/>
        <source>Impossibile salvare il file dei profili dopo aver aggiunto &apos;{0}&apos;.</source>
        <translation>Unable to save profile file after adding &apos;{0}&apos;.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="242"/>
        <source>Selezione mondo annullata o fallita.</source>
        <translation>World selection canceled or failed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="245"/>
        <source>Selezione mondo annullata.</source>
        <translation>World selection canceled.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="311"/>
        <source>Errore Dipendenza</source>
        <translation>Dependency Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="311"/>
        <source>La libreria &apos;winshell&apos; necessaria non è installata.</source>
        <translation>The required &apos;winshell&apos; library is not installed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="315"/>
        <source>Errore Collegamento</source>
        <translation>Link Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="315"/>
        <source>Impossibile leggere il file .lnk:
{0}</source>
        <translation>Cannot read .lnk file:
{0}</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="328"/>
        <source>Impossibile generare un nome profilo valido dal collegamento trascinato.</source>
        <translation>Unable to generate a valid profile name from the dragged link.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="332"/>
        <source>Profilo &apos;{0}&apos; esiste già.</source>
        <translation>Profile &apos;{0}&apos; already exists.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="337"/>
        <source>Operazione in Corso</source>
        <translation>Operation in Progress</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="337"/>
        <source>Un&apos;altra ricerca di percorso è già in corso. Attendi.</source>
        <translation>Another route search is already in progress. Hold.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="341"/>
        <source>Ricerca percorso per &apos;{0}&apos; in corso...</source>
        <translation>Path search for &apos;{0}&apos; in progress...</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="373"/>
        <source>Ricerca percorso completata.</source>
        <translation>Path search completed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="380"/>
        <source>Errore sconosciuto durante la ricerca.</source>
        <translation>Unknown error during search.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="382"/>
        <source>Errore Ricerca Percorso</source>
        <translation>Path Search Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="384"/>
        <source>Ricerca interrotta.</source>
        <translation>Search aborted.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="397"/>
        <source>Conferma Percorso Automatico</source>
        <translation>Confirm Automatic Route</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="399"/>
        <source>È stato rilevato questo percorso:

{0}

Vuoi usarlo per il profilo &apos;{1}&apos;?</source>
        <translation>This path was detected:

{0}

Do you want to use it for profile &apos;{1}&apos;?</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="408"/>
        <location filename="gui_components/profile_creation_manager.py" line="475"/>
        <location filename="gui_components/profile_creation_manager.py" line="499"/>
        <source>Creazione profilo annullata.</source>
        <translation>Profile creation cancelled.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="444"/>
        <source>[Inserisci Manualmente...]</source>
        <translation>[Insert Manually...]</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="453"/>
        <source>Conferma Percorso Salvataggi</source>
        <translation>Confirm Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="454"/>
        <source>Sono stati trovati questi percorsi potenziali per &apos;{0}&apos;.
Seleziona quello corretto (ordinati per probabilità) o scegli l&apos;inserimento manuale:</source>
        <translation>These potential paths for &apos;{0}&apos; were found.
Select the correct one (sorted by probability) or choose manual entry:</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="480"/>
        <source>Percorso Non Rilevato</source>
        <translation>Path Not Detected</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="480"/>
        <source>Impossibile rilevare automaticamente il percorso dei salvataggi per &apos;{0}&apos;.
Per favore, inseriscilo manualmente.</source>
        <translation>Unable to automatically detect save path for &apos;{0}&apos;.
Please enter it manually.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="484"/>
        <source>Errore interno durante la gestione dei risultati.</source>
        <translation>Internal error while handling results.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="490"/>
        <source>Inserisci il percorso COMPLETO per i salvataggi del profilo:
&apos;{0}&apos;</source>
        <translation>Enter the FULL path for profile saves:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="491"/>
        <source>Percorso Salvataggi Manuale</source>
        <translation>Manual Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="496"/>
        <source>Creazione profilo annullata (percorso vuoto).</source>
        <translation>Profile creation cancelled (empty path).</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="515"/>
        <source>Profilo &apos;{0}&apos; creato con successo.</source>
        <translation>Profile &apos;{0}&apos; successfully created.</translation>
    </message>
</context>
<context>
    <name>self.main_window</name>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="39"/>
        <source>Profilo</source>
        <translation>Profile</translation>
    </message>
    <message>
        <source>Info Backup</source>
        <translation type="vanished">Info Backup</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="80"/>
        <source>Nessun profilo creato.</source>
        <translation>No profile created.</translation>
    </message>
    <message>
        <source>Backup</source>
        <translation type="vanished">Backup</translation>
    </message>
    <message>
        <source>Backups</source>
        <translation type="vanished">Backups</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="122"/>
        <source>Ultimo</source>
        <translation>Last</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="127"/>
        <source>Nessun backup</source>
        <translation>No backup</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="86"/>
        <source>Passa al tema scuro</source>
        <translation>switch to dark theme</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="97"/>
        <source>Passa al tema chiaro</source>
        <translation>Switch to light theme</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="129"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="130"/>
        <source>Impossibile salvare l&apos;impostazione del tema.</source>
        <translation>Unable to save theme settings.</translation>
    </message>
</context>
</TS>
